In [1]:
lst = []
lst = [1,2,3]

In [2]:
lst.append(4)

In [3]:
lst

[1, 2, 3, 4]

In [4]:
lst.insert(1,4)

In [5]:
lst

[1, 4, 2, 3, 4]

In [6]:
lst.extend([6,7])

In [7]:
lst

[1, 4, 2, 3, 4, 6, 7]

In [9]:
lst += [8,9]
lst

[1, 4, 2, 3, 4, 6, 7, 8, 9, 8, 9]

In [11]:
del lst[1]
lst

[1, 2, 3, 4, 6, 7, 8, 9, 8, 9]

In [12]:
lst.pop(1)
lst

[1, 3, 4, 6, 7, 8, 9, 8, 9]

In [13]:
lst.pop()
lst

[1, 3, 4, 6, 7, 8, 9, 8]

In [14]:
lst.clear()
lst

[]

In [15]:
lst = [1,2,3]

In [16]:
lst += [6,3,7,4]
lst.sort()

In [17]:
lst

[1, 2, 3, 3, 4, 6, 7]

In [19]:
lst.clear()
lst += [1,3,6,3,6,7,4,3]
sorted(lst)

[1, 3, 3, 3, 4, 6, 6, 7]

In [20]:
lst = [4,2,3,1]
lst.reverse()
lst

[1, 3, 2, 4]

In [21]:
lstA =[4,2,3,1]
lstB = list(reversed(lstA))
print(lstA)
print(lstB)

[4, 2, 3, 1]
[1, 3, 2, 4]


In [22]:
import copy
lstA =[4,2,3,1]
lstB = copy.copy(lstA)
lstB.sort()
print(lstB)
print(lstA)

[1, 2, 3, 4]
[4, 2, 3, 1]


In [23]:
lstA = [4,2,3,1]
lstB = lstA[:]
lstB.sort()
print(lstB)
print(lstA)

[1, 2, 3, 4]
[4, 2, 3, 1]


In [25]:
lstA = [[1,3],[1,2,3],[3,2]]
print(lstA)

lstB = []
for i in lstA:
    for j in i:
        lstB.append(j)
print(lstB)

[[1, 3], [1, 2, 3], [3, 2]]
[1, 3, 1, 2, 3, 3, 2]


In [27]:
[j for i in lstA for j in i]

[1, 3, 1, 2, 3, 3, 2]

In [28]:
lstA = [[1,3],[1,2,3],[3,2]]
sum(lstA,[])

[1, 3, 1, 2, 3, 3, 2]

In [31]:
import numpy as np

x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
print(x[-2])

8


In [33]:
x = np.arange(25).reshape(5,5)

In [34]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [35]:
x.reshape(1,25)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [40]:
print(x[0,:3])

[0 1 2]


In [41]:
print(x[3:])

[[15 16 17 18 19]
 [20 21 22 23 24]]


In [42]:
x<10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [45]:
IsOver10 = x<10
Is2Times = x%2==0

In [46]:
Is2Times

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [47]:
x[x<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
Is2Times = x[x%2==0]
Is2Times

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [51]:
Is2Times[:]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [52]:
X = np.arange(24,-1,-1).reshape(5,5)
X[[1,3],:]

array([[19, 18, 17, 16, 15],
       [ 9,  8,  7,  6,  5]])

In [53]:
X[[3,4],:]

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [54]:
print(Is2Times)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24]


In [56]:
print(X)
print(X[1:3,::-1])

[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]
[[15 16 17 18 19]
 [10 11 12 13 14]]


In [69]:
print(X[1:3,::-1])

[[15 16 17 18 19]
 [10 11 12 13 14]]


In [80]:
print(X[[1,3],::-1])
print(X[1:3,::-1])

[[15 16 17 18 19]
 [ 5  6  7  8  9]]
[[15 16 17 18 19]
 [10 11 12 13 14]]


In [82]:
print(X[:,[0,2]])

[[24 22]
 [19 17]
 [14 12]
 [ 9  7]
 [ 4  2]]


In [83]:
print(X[[1,3],[0,2]])

[19  7]


In [84]:
X[np.ix_([1,3],[0,2])]

array([[19, 17],
       [ 9,  7]])

In [86]:
np.ix_([1,3],[1,2])

(array([[1],
        [3]]),
 array([[1, 2]]))

In [87]:
print(np.ix_([1,3],[1,2]))

(array([[1],
       [3]]), array([[1, 2]]))


In [88]:
i,j = X.nonzero()

In [89]:
i

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4])

In [90]:
j

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3])

In [91]:
X[i,j]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1])

In [92]:
print(X)

[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


In [94]:
print(X[i,j])

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [95]:
i,j = np.where(X!=0)

In [96]:
print(X[i,j])

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [125]:
x = np.arange(5)
y = np.arange(4,-1,-1)
np.hstack((x,y)) 

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [126]:
x_reshape = x.reshape(len(x),1)
y_reshape = y.reshape(len(y),1)
print(x_reshape)
print(y_reshape)

[[0]
 [1]
 [2]
 [3]
 [4]]
[[4]
 [3]
 [2]
 [1]
 [0]]


In [131]:
vertical = np.hstack((x_reshape,y_reshape))
vertical

array([[0, 4],
       [1, 3],
       [2, 2],
       [3, 1],
       [4, 0]])

In [132]:
horizon = np.vstack((x_reshape,y_reshape))
horizon

array([[0],
       [1],
       [2],
       [3],
       [4],
       [4],
       [3],
       [2],
       [1],
       [0]])

In [139]:
from itertools import islice
horizon2 = horizon.reshape(len(horizon)//2,2)
horizon2

array([[0, 1],
       [2, 3],
       [4, 4],
       [3, 2],
       [1, 0]])

In [141]:
horizon3 = horizon.reshape(2,len(horizon)//2)
horizon3

array([[0, 1, 2, 3, 4],
       [4, 3, 2, 1, 0]])

In [165]:
length_to_split = [len(horizon)//2]*2
lst = iter(horizon)
#output = [list(islice(lst,elem)) for elem in length_to_split]
for elem in length_to_split:
    output = list(islice(lst,5))
    print(output)
print("Initial list:",horizon)
#print("After splitting:",output)

[array([0]), array([1]), array([2]), array([3]), array([4])]
[array([4]), array([3]), array([2]), array([1]), array([0])]
Initial list: [[0]
 [1]
 [2]
 [3]
 [4]
 [4]
 [3]
 [2]
 [1]
 [0]]


In [146]:
print(length_to_split)

[5, 5]


In [147]:
a = [12,0.38,"abc","DEF",1000]
i = iter(a)

for j in i:
    print(j)

12
0.38
abc
DEF
1000


In [174]:

Input = 'ABCDEFG'
Input = iter(Input)
result = list(islice(Input,2))
print(result)
#result = list(islice(Input,2))
print(list(Input))

['A', 'B']
['C', 'D', 'E', 'F', 'G']


セッターが呼ばれました
ゲッターが呼ばれました
マイケル
